<!DOCTYPE html>
<html>
<head>
    <title>Block OR Not</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    <header>
    <nav>
        <div class="nav-wrapper amber darken-4">
            <a href="./" class="center brand-logo">Block OR Not</a>
        </div>
    </nav>
    </header>

    <main>
    <div class="container">
        <div class="row">
            <div class="col s12">
                <p>They know too much, should we block them?</p>
            </div>
        </div>

        % for _, category in output.items():
        <div
         class="row category"
         data-_category_id="{{category['category_id']}}"
         data-_name="{{category['name']}}">
            <div class="col s12">
                <div class="card amber darken-2">
                    <div class="card-image">
                        <img style="visibility: hidden" height="100" />
                        <span class="card-title">{{category['name']}}</span>
                        <a class="refresh btn-floating halfway-fab waves-effect waves-light light-green darken-2"><i class="material-icons">refresh</i></a>
                    </div>
                    <div class="card-content white">
                        <table>
                            <thead>
                                <tr>
                                    <th>Website</th>
                                    <th>Time</th>
                                    <th>Status</th>
                                </tr>
                            </thead>

                            <tbody>
                                % for website in category['website_list']:
                                <tr
                                 data-_website_uri="{{website['website_uri']}}"
                                 data-_country="{{website['country']}}"
                                 data-_category_id="{{website['category_id']}}"
                                 data-_search_input="{{website['search_input']}}"
                                 data-_anomaly="{{website['content']['results'][0]['anomaly']}}"
                                 data-_failure="{{website['content']['results'][0]['failure']}}"
                                 data-_time="{{website['content']['results'][0]['measurement_start_time']}}"
                                 data-_confirmed="{{website['content']['results'][0]['confirmed']}}">
                                    <td>{{website['website_uri']}}</td>
                                    <td>{{website['content']['results'][0]['measurement_start_time']}}</td>
                                    % if website['content']['results'][0]['anomaly']:
                                    <td class="red lighten-5 red-text text-darken-4">BLOCK</td>
                                    % else:
                                    <td class="center-align green lighten-5 green-text text-darken-4">OK</td>
                                    % end
                                </tr>
                                % end
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        % end
    </div>
    </main>

    <footer class="page-footer blue-grey darken-4 grey-text text-lighten-5">
    <div class="container">
        <div class="row">
            <div class="col s8">
                <h5>Block OR Not</h5>
                <p>Feel free to send us a feature request or pull requests via our <a href="https://github.com/Jeffrey04/blockornot-neo">github repository</a></p>
            </div>
            <div class="col s4">
                <h5 class="white-text">Related Links</h5>
                <ul>
                  <li><a href="https://blockornot.today/">Home</a></li>
                  <li><a href="https://sinarproject.org/">Sinar Project</a></li>
                  <li><a href="https://github.com/Jeffrey04/blockornot-neo/">Our github repository</a></li>
                  <li><a href="https://cilisos.my/how-to-unblock-sarawak-report-in-5-minutes/">Tips and tricks</a></li>
                </ul>
              </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <p>
                    Site is hosted by <a href="https://coolsilon.com">coolsilon.com</a>. No rights reserved.
                    </p>
                </div>
            </div>
        </div>
    </div>
    </footer>
    <template id="preloader">
    <div class="preloader-wrapper small active">
      <div class="spinner-layer spinner-blue">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>

      <div class="spinner-layer spinner-red">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>

      <div class="spinner-layer spinner-yellow">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>

      <div class="spinner-layer spinner-green">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>
    </div>
    </template>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/redux/3.7.2/redux.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js"></script>
    <script type="text/javascript" src="./static/app.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-117126231-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '{{tracking_code}}');
    </script>
</body>
</html>